trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildTestAndRun
  displayName: 'Build, Test, and Run Application'
  steps:
  - script: |
      # Build the Docker image for your Node.js application
      docker build -t my-node-app:latest .

      # Run the Docker container for your Node.js application
      docker run -d -p 3000:3000 my-node-app:latest

      # Wait for the application to be ready (using wait-for-it.sh)
      ./wait-for-it.sh localhost:3000 -- timeout 60s

      # Change directory to the tests folder
      cd tests

      # Run your tests (assuming your tests point to the Docker container)
      npm test
    displayName: 'Build, Run, and Test'