trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  DOMAIN_URL: 'https://node-app-testing-week.azurewebsites.net/'  # Define the variable at the pipeline level

stages:
- stage: BuildAndPushContainer
  jobs:
  - job: BuildAndRun
    displayName: 'Build and Push Image'
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: nodeappcr
        repository: 'nodeappcr-repo'
        Dockerfile: Dockerfile
        tags: |
          $(Build.BuildId)

- stage: DeployApp
  jobs:
  - job: DeployApp
    displayName: 'Deploy App'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App on Container Deploy: node-app-testing-week'
      inputs:
        azureSubscription: 'Azure subscription 1 (29a26c0c-0f8e-4781-9ba4-0025694db2d4)'
        appName: 'node-app-testing-week'
        containers: 'nodeappcr.azurecr.io/nodeappcr-repo:$(Build.BuildId)'
    
    - script: |
        echo "Variable Value: $DOMAIN_URL"
      displayName: 'Set Container URL'

- stage: RunTests
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        export DOMAIN_URL=$DOMAIN_URL  # Set DOMAIN_URL as a process environment variable
        npm install
        npm test
      workingDirectory: tests
      displayName: 'Run Tests'
