trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndRunContainer
  jobs:
  - job: BuildAndRun
    displayName: 'Build and Run Application Container'
    steps:
    - script: |
        # Build the Docker image for your Node.js application
        docker build -t my-node-app:latest .

        # Run the Docker container for your Node.js application
        docker run -d -p 3000:3000 my-node-app:latest

        docker inspect my-node-app

        # Retrieve the container's IP address
        container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' my-node-app)

        # container_ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -q))

        # Print the container's IP address
        echo "Container IP address: $container_ip"

        # Set the container's IP address as an environment variable
        echo "##vso[task.setvariable variable=CONTAINER_IP]$container_ip"

        echo "Environment variables:"
        env
      displayName: 'Build and Run Application'

- stage: Test
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        # Move to the tests folder
        cd tests
        npm install
        
        # Run your tests (assuming your tests point to the Docker container)
        npm test
      displayName: 'Run Tests'