trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: BuildAndPushContainer
  jobs:
  - job: BuildAndRun
    displayName: 'Build and Push Image'
    steps:
    - task: Docker@2
      displayName: 'Build and Push'
      inputs:
        containerRegistry: nodeappcr
        repository: 'nodeappcr-repo'
        Dockerfile: Dockerfile
        tags: |
          $(Build.BuildId)

- stage: DeployApp
  jobs:
  - job: DeployApp
    displayName: 'Deploy App'
    steps:
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App on Container Deploy: node-app-testing-week'
      inputs:
        azureSubscription: 'Azure subscription 1 (29a26c0c-0f8e-4781-9ba4-0025694db2d4)'
        appName: 'node-app-testing-week'
        containers: 'nodeappcr.azurecr.io/nodeappcr-repo:$(Build.BuildId)'
    
    - script: |
        echo "##vso[task.setvariable variable=CONTAINER_IP;isOutput=true]https://node-app-testing-week.azurewebsites.net/"
        echo "Variable Value: $CONTAINER_IP"
      displayName: 'Set Container IP'

- stage: RunTests
  jobs:
  - job: RunTests
    displayName: 'Run Tests'
    steps:
    - script: |
        npm install
        npm test
      workingDirectory: tests
      displayName: 'Run Tests'